import os
import datetime
import logging
import asyncio
from typing import List, Dict, Any, Optional

from ai_assistant.memory.vector_store import VectorStore
from ai_assistant.llm_interface.ollama_client import OllamaProvider

from ai_assistant.config import get_data_dir, DEFAULT_MODEL

logger = logging.getLogger(__name__)

class EpisodicMemoryManager:
    """
    Manages episodic memory (experiences) to allow the AI to learn from past actions,
    successes, and failures.
    """
    def __init__(self, collection_name: str = "episodic_logs"):
        self.storage_path = os.path.join(get_data_dir(), "episodic_vector_store.json")
        self.collection_name = collection_name
        self.vector_store = VectorStore(self.storage_path, collection_name=self.collection_name)
        self.ollama_provider = OllamaProvider()


    async def recall_failures(self, prompt: str, k: int = 3, score_threshold: float = 0.35) -> Optional[str]:
        """
        Recalls relevant past failures for a given prompt.
        Returns a warning string if failures are found, else None.
        """
        try:
            embedding = await self.ollama_provider.get_embeddings_async(prompt)
            if not embedding:
                return None

            # Fix: Pass filter_criteria to search ONLY for failures at the DB level
            results = self.vector_store.search(
                embedding, 
                k=k, 
                score_threshold=score_threshold,
                filter_criteria={"outcome": "FAILURE"}
            )

            if not results:
                return None

            # Construct warning message
            warnings = []
            for fail in results:
                metadata = fail.get("metadata", {})
                date = metadata.get("timestamp", "Unknown Date")
                lesson = metadata.get("lesson", "No specific lesson recorded.")
                warnings.append(f"- [Date: {date}] Lesson: {lesson}")

            if warnings:
                return "WARNING: You attempted a similar task in the past and it FAILED. Review the lessons:\n" + "\n".join(warnings)

            return None

        except Exception as e:
            logger.error(f"Error in recall_failures: {e}")
            return None

    async def record_experience(self, prompt: str, plan: Optional[List[Dict[str, Any]]], outcome: str, tools_used: List[str]) -> str:
        """
        Records an experience (success or failure) to the episodic logs.
        Includes a "Lesson Learned" generated by the LLM.
        Returns the generated lesson.
        """
        lesson = "No lesson generated."
        try:
            # Generate Lesson Learned
            lesson = await self._generate_lesson(prompt, plan, outcome, tools_used)

            # Construct document content
            # document: The user prompt + the plan (summarized)
            plan_str = str(plan) if plan else "No plan"
            document_text = f"Goal: {prompt}\nPlan: {plan_str}\nOutcome: {outcome}"

            # Fix: Generate embedding based on PROMPT ONLY to match recall query
            embedding = await self.ollama_provider.get_embeddings_async(prompt)
            if not embedding:
                logger.error("Failed to generate embedding for episodic log.")
                return lesson

            # Metadata
            metadata = {
                "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                "outcome": outcome,
                "tools_used": ", ".join(tools_used),
                "lesson": lesson
            }

            # Save to VectorStore
            self.vector_store.add_documents([document_text], [embedding], [metadata])
            logger.info(f"Recorded episodic experience: {outcome}")
            
            return lesson

        except Exception as e:
            logger.error(f"Error recording experience: {e}")
            return lesson

    async def _generate_lesson(self, prompt: str, plan: Optional[List[Dict[str, Any]]], outcome: str, tools_used: List[str]) -> str:
        """
        Asks the LLM to summarize the lesson learned in 1 sentence.
        """
        system_prompt = f"""You are analyzing an AI's execution log to extract a lesson.
Goal: {prompt}
Outcome: {outcome}
Tools Used: {tools_used}

Task: Provide a ONE-SENTENCE "Lesson Learned" from this experience.
If it was a FAILURE, explain what went wrong and what to avoid.
If it was a SUCCESS, summarize the key action that worked.
"""
        # Fix: Use self.ollama_provider to respect config settings (provider agnostic)
        response = await self.ollama_provider.invoke_ollama_model_async(
            prompt=system_prompt, 
            model_name=DEFAULT_MODEL
        )
        return response.strip() if response else "No lesson generated."
