import os
import datetime
import logging
import asyncio
from typing import List, Dict, Any, Optional

from ai_assistant.memory.vector_store import VectorStore
from ai_assistant.llm_interface.ollama_client import OllamaProvider

from ai_assistant.config import get_data_dir, DEFAULT_MODEL
from ai_assistant.core.failure_freshness import annotate_failure_metadata, is_failure_stale

logger = logging.getLogger(__name__)

class EpisodicMemoryManager:
    """
    Manages episodic memory (experiences) to allow the AI to learn from past actions,
    successes, and failures.
    """
    def __init__(self, collection_name: str = "episodic_logs"):
        self.storage_path = os.path.join(get_data_dir(), "episodic_vector_store.json")
        self.collection_name = collection_name
        self.vector_store = VectorStore(self.storage_path, collection_name=self.collection_name)
        self.ollama_provider = OllamaProvider()


    async def recall_failures(self, prompt: str, k: int = 3, score_threshold: float = 0.35) -> Optional[str]:
        """
        Recalls relevant past failures for a given prompt.
        Returns a warning string if failures are found, else None.
        """
        try:
            embedding = await self.ollama_provider.get_embeddings_async(prompt)
            if not embedding:
                return None

            # Fix: Pass filter_criteria to search ONLY for failures at the DB level
            results = self.vector_store.search(
                embedding, 
                k=k, 
                score_threshold=score_threshold,
                filter_criteria={"outcome": "FAILURE"}
            )

            if not results:
                return None

            # Construct warning message
            warnings = []
            for fail in results:
                metadata = fail.get("metadata", {})
                if is_failure_stale(metadata, metadata.get("timestamp")):
                    continue
                date = metadata.get("timestamp", "Unknown Date")
                lesson = metadata.get("lesson", "No specific lesson recorded.")
                warnings.append(f"- [Date: {date}] Lesson: {lesson}")

            if warnings:
                return "WARNING: You attempted a similar task in the past and it FAILED. Review the lessons:\n" + "\n".join(warnings)

            return None

        except Exception as e:
            logger.error(f"Error in recall_failures: {e}")
            return None

    async def record_experience(self, prompt: str, plan: Optional[List[Dict[str, Any]]], outcome: str, tools_used: List[str]) -> str:
        """
        Records an experience (success or failure) to the episodic logs.
        Includes a "Lesson Learned" generated by the LLM.
        Returns the generated lesson.
        """
        lesson = "No lesson generated."
        try:
            # Generate Lesson Learned
            lesson = await self._generate_lesson(prompt, plan, outcome, tools_used)

            # Construct document content
            # document: The user prompt + the plan (summarized)
            plan_str = str(plan) if plan else "No plan"
            document_text = f"Goal: {prompt}\nPlan: {plan_str}\nOutcome: {outcome}"

            # Fix: Generate embedding based on PROMPT ONLY to match recall query
            embedding = await self.ollama_provider.get_embeddings_async(prompt)
            if not embedding:
                logger.error("Failed to generate embedding for episodic log.")
                return lesson

            # Metadata
            metadata = {
                "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                "outcome": outcome,
                "tools_used": ", ".join(tools_used),
                "lesson": lesson
            }
            if outcome == "FAILURE":
                annotate_failure_metadata(metadata, metadata["timestamp"])

            # Save to VectorStore
            self.vector_store.add_documents([document_text], [embedding], [metadata])
            logger.info(f"Recorded episodic experience: {outcome}")
            
            return lesson

        except Exception as e:
            logger.error(f"Error recording experience: {e}")
            return lesson

    async def _generate_lesson(self, prompt: str, plan: Optional[List[Dict[str, Any]]], outcome: str, tools_used: List[str]) -> str:
        """
        Asks the LLM to summarize the lesson learned in 1 sentence.
        """
        system_prompt = f"""You are analyzing an AI's execution log to extract a lesson.
Goal: {prompt}
Outcome: {outcome}
Tools Used: {tools_used}

Task: Provide a ONE-SENTENCE "Lesson Learned" from this experience.
If it was a FAILURE, explain what went wrong and what to avoid.
If it was a SUCCESS, summarize the key action that worked.
"""
        # Fix: Use self.ollama_provider to respect config settings (provider agnostic)
        response = await self.ollama_provider.invoke_ollama_model_async(
            prompt=system_prompt, 
            model_name=DEFAULT_MODEL
        )
        return response.strip() if response else "No lesson generated."

    async def background_prune_and_summarize(self, max_records: int = 50, prune_count: int = 10):
        """
        Runs a background process to check if the episodic memory has grown too large.
        If it exceeds `max_records`, it takes the oldest `prune_count` records,
        summarizes them into a single "Archived Knowledge Summary", and deletes the originals.
        """
        try:
            records = self.vector_store.get_all()
            if not records or len(records) <= max_records:
                return # Nothing to do

            logger.info(f"Episodic memory threshold reached ({len(records)} > {max_records}). Pruning oldest {prune_count} records.")

            # Sort by timestamp ascending (oldest first)
            def parse_time(r):
                ts = r.get("metadata", {}).get("timestamp")
                if ts:
                    try:
                        return datetime.datetime.fromisoformat(ts).timestamp()
                    except:
                        pass
                return 0 # Fallback 

            sorted_records = sorted(records, key=parse_time)
            target_records = sorted_records[:prune_count]

            if not target_records: return

            # Combine texts for the LLM
            combined_texts = []
            for i, rec in enumerate(target_records):
                 text = rec.get("text", "")
                 meta = rec.get("metadata", {})
                 combined_texts.append(f"Episode {i+1}: {text}\nLesson from Episode {i+1}: {meta.get('lesson', 'None')}")

            full_context = "\n\n---\n".join(combined_texts)

            # Summarization Prompt
            summary_prompt = f"""You are an AI archivist. Your job is to compress older, granular episodic memories into a single, dense 'Archived Knowledge Summary'.
You will be given {len(target_records)} past experiences. Find the common threads, failures, and overarching lessons, and condense them into a highly compact summary.

PAST EXPERIENCES:
{full_context}

Condense the core wisdom into a single paragraph of dense concepts."""

            summary = await self.ollama_provider.invoke_ollama_model_async(
                prompt=summary_prompt,
                model_name=DEFAULT_MODEL
            )
            
            if not summary:
                 logger.error("Failed to generate archive summary. Aborting prune.")
                 return

            # Record the new combined archive
            archive_doc = f"ARCHIVED EXPERIENCES SUMMARY: {summary.strip()}"
            embedding = await self.ollama_provider.get_embeddings_async(archive_doc)

            if embedding:
                metadata = {
                    "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                    "outcome": "ARCHIVED_SUMMARY",
                    "lesson": summary.strip()
                }
                
                self.vector_store.add_documents([archive_doc], [embedding], [metadata])
                
                # If addition succeeded, delete the old discrete records
                ids_to_delete = [r["id"] for r in target_records]
                self.vector_store.delete(ids_to_delete)
                logger.info(f"Successfully pruned {len(ids_to_delete)} records and created highly compressed archive.")
            else:
                 logger.error("Failed to generate embedding for the archive summary.")

        except Exception as e:
            logger.error(f"Error in background_prune_and_summarize: {e}")
